"""Segunda migración - ahora sí tablas

Revision ID: 1e9915380a08
Revises: c1578c5712ea
Create Date: 2025-04-27 12:30:47.791300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e9915380a08'
down_revision = 'c1578c5712ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conductor_id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conductor_id'], ['conductor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacion')
    # ### end Alembic commands ###
