"""Add is_active to conductor model

Revision ID: bed76f73b00f
Revises: 1e9915380a08
Create Date: 2025-04-28 06:22:46.314066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed76f73b00f'
down_revision = '1e9915380a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conductor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conductor', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
