"""Agregar placa, modelo y year a Unidad

Revision ID: c1578c5712ea
Revises: 17fd314a47cf
Create Date: 2025-04-27 11:41:54.869450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1578c5712ea'
down_revision = '17fd314a47cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('placa', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('modelo', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidad', schema=None) as batch_op:
        batch_op.drop_column('year')
        batch_op.drop_column('modelo')
        batch_op.drop_column('placa')

    # ### end Alembic commands ###
